// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnyrvcekervaoriyilss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRueXJ2Y2VrZXJ2YW9yaXlpbHNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MDE1MjcsImV4cCI6MjA2MTM3NzUyN30.nRXzByhzb8vU7PyBzSvk2A9zeEP5gMvVh5A6BNoiIMA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);